[package]
name = "cloud-zip-ext"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.65.0"
tokio = { version = "1", features = ["full"] }
